apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-budget

resources:
  - ../deployment

nameSuffix: -blue

labels:
  - includeSelectors: true
    pairs:
      version: blue

images:
  - name: simple-budget
    newName: ghcr.io/corybuecker/simple-budget
    digest: sha256:b16965f753a866982502bd81cab00b85f47b5212d5aaed4d61c35eb8948813cf
