apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-budget

resources:
  - ../deployment

nameSuffix: -blue

labels:
  - includeSelectors: true
    pairs:
      version: blue

images:
  - name: simple-budget
    newName: projects.corybuecker.dev/corybuecker/simple-budget
    digest: sha256:24edbaee1f3e273a1773d9483eba3d5c2e5ffa97303d2dd32e2785cb39303c03
