FROM elixir:1.7.4-alpine

ENV MIX_ENV=dev

RUN apk update && apk add git nodejs npm gmp

COPY mix.exs mix.lock /app/

COPY assets/package-lock.json assets/package.json /app/assets/

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

RUN mix deps.get && \
    mix deps.compile

RUN cd assets && \
    npm install

ENV PATH=/app/assets/node_modules/.bin:$PATH

COPY . /app

EXPOSE 4000

CMD ["mix", "phx.server"]

LABEL maintainer="cory.buecker@gmail.com"
