version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "4000:4000"
    environment:
      HOSTNAME: "database"
    depends_on:
      - database
  database:
    image: "postgres:10"