apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-cast
  namespace: simple-budget
  labels:
    app: container-cast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-cast
  template:
    metadata:
      labels:
        app: container-cast
    spec:
      serviceAccountName: container-cast
      containers:
      - name: container-cast
        image: ${IMAGE}/container-cast:latest
        ports:
        - name: http
          containerPort: 3000
        envFrom:
        - secretRef:
            name: container-cast
