apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: simple-budget
  name: deployer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["simple-budget"]
  verbs: ["get", "patch"]
