apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simple-budget
  namespace: simple-budget
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer
subjects:
- kind: ServiceAccount
  name: container-cast
  namespace: simple-budget
