apiVersion: v1
kind: Service
metadata:
  name: container-cast
  namespace: simple-budget
spec:
  selector:
    app: container-cast
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
