services:
  postgres:
    image: postgres@sha256:073e7c8b84e2197f94c8083634640ab37105effe1bc853ca4d5fbece3219b0e8 # 18
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: simple_budget
      POSTGRES_USER: simple_budget
    volumes:
      - ../migrations/schema.sql:/docker-entrypoint-initdb.d/0000.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/0001.sql
  prometheus:
    image: prom/prometheus@sha256:339ce86a59413be18d0e445472891d022725b4803fab609069110205e79fb2f1 # v3.3.0
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-otlp-receiver
  jaeger:
    image: jaegertracing/jaeger@sha256:20d715ade1cf32e8c2be1a288317c2126376ce60811be71f0856793d7f849127 # 2.5.0
    ports:
      - 16686:16686
      - 4318:4318
