services:
  postgres:
    image: postgres@sha256:6efd0df010dc3cb40d5e33e3ef84acecc5e73161bd3df06029ee8698e5e12c60 # 17.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: simple_budget
      POSTGRES_USER: simple_budget
    volumes:
      - ../migrations/schema.sql:/docker-entrypoint-initdb.d/0000.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/0001.sql
  prometheus:
    image: prom/prometheus@sha256:339ce86a59413be18d0e445472891d022725b4803fab609069110205e79fb2f1 # v3.3.0
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-otlp-receiver