apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-budget
  namespace: simple-budget
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
  - hosts:
    - ${HOST}
    secretName: tls
  rules:
  - host: ${HOST}
    http:
      paths:
      - path: /github
        pathType: Exact
        backend:
          service:
            name: container-cast
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-budget
            port:
              name: http
  ingressClassName: nginx
