apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-budget

resources:
  - ../deployment

nameSuffix: -green

labels:
  - includeSelectors: true
    pairs:
      version: green

images:
  - name: simple-budget
    newName: ghcr.io/corybuecker/simple-budget
    digest: sha256:e1c954817f8f70f4d2e6679b1c7ed228d80e756eca71511dcf842e4e40b4434a
