apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-budget
  labels:
    app: simple-budget
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple-budget
  template:
    metadata:
      labels:
        app: simple-budget
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/arch: arm64
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: simple-budget
          image: simple-budget:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: simple-budget-config
            - secretRef:
                name: simple-budget-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
