apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: simple-budget
  labels:
    app: simple-budget
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /healthcheck
  targetRef:
    group: ""
    kind: Service
    name: simple-budget
