apiVersion: v1
kind: Service
metadata:
  name: simple-budget
  labels:
    app: simple-budget
spec:
  type: ClusterIP
  selector:
    app: simple-budget
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
