apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-budget

resources:
  - namespace.yaml
  - configmap.yaml
  # - networkpolicies.yaml
  # - httproute.yaml
  # - gateway.yaml

secretGenerator:
- name: simple-budget
  envs:
  - secrets.env
