name: branch-protection
permissions:
  contents: read
on:
  pull_request:
    branches: main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo clippy --no-deps -- -D warnings
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "mongodb://localhost:27017/simple_budget?retryWrites=true&w=majority&directConnection=true"
    steps:
      - run: docker run --name mongo -d -p 27017:27017 mongo:8.0.4 --replSet rs0
      - run: docker exec mongo mongosh --eval "rs.initiate()"
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
  build:
    runs-on: ubuntu-24.04-arm
    needs:
      - lint
      - test
    permissions:
      packages: write
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/corybuecker/simple-budget:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max