name: branch-protection
permissions:
  contents: read
on:
  pull_request:
    branches: main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo clippy --no-deps -- -D warnings
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "mongodb://localhost:27017/simple_budget?retryWrites=true&w=majority&directConnection=true"
    steps:
      - run: docker run --name mongo -d -p 27017:27017 mongo:8.0.4 --replSet rs0
      - run: docker exec mongo mongosh --eval "rs.initiate()"
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
