name: branch-protection
permissions:
  contents: read
on:
  pull_request:
    branches: main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo clippy --no-deps -- -D warnings
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --name postgres -d -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_DB=simple_budget_test -v ./schema.sql:/docker-entrypoint-initdb.d/schema.sql postgres:17.4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
  build:
    runs-on: ubuntu-24.04-arm
    needs:
      - lint
      - test
    permissions:
      packages: write
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/corybuecker/simple-budget:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
