name: branch-protection
permissions:
  contents: read
on:
  pull_request:
    branches: main
jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: |
          sed -i "s/version: [0-9]\{10\}/version: $(date +%s)/" k8s/deployment.yaml
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "chore: versioned"
          git push
  lint:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo clippy --no-deps -- -D warnings
  test:
    runs-on: ubuntu-latest
    needs: version
    env:
      DATABASE_URL: "mongodb://localhost:27017/simple_budget?retryWrites=true&w=majority&directConnection=true"
    steps:
      - run: docker run --name mongo -d -p 27017:27017 mongo:8.0.4 --replSet rs0
      - run: docker exec mongo mongosh --eval "rs.initiate()"
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
