name: CI
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    container: elixir:1.9.0
    services:
      postgres:
        image: postgres:11-alpine
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      env:
        MIX_ENV: test
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.compile
    - name: Run Tests
      env:
        MIX_ENV: test
        TEST_DATABASE_URL: postgres://postgres@postgres:5432/simple_budget_test
      run: |
        mix test
        mix credo --strict
