name: continuous-delivery
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: sudo apt install gcc-aarch64-linux-gnu -y
    - run: rustup target install aarch64-unknown-linux-gnu
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: npm install tailwindcss @tailwindcss/container-queries @tailwindcss/forms
    - run: npx tailwindcss -i input.css -o static/app.css
    - run: cargo build --release --target aarch64-unknown-linux-gnu
    - uses: actions/upload-artifact@v4
      with:
        name: simple-budget
        path: target/aarch64-unknown-linux-gnu/release/simple-budget
    - uses: docker/setup-buildx-action@v3
    - uses: actions/download-artifact@v4
      with:
        name: simple-budget
    - uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64/v8
        context: .
        push: true
        tags: ghcr.io/corybuecker/simple-budget:latest