name: continuous-delivery
permissions:
  contents: read
  packages: write
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/corybuecker/simple-budget:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
